[package]
name = "naval-battle-game-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15"}
env_logger = "0.9"
log = "0.4"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
